version: '3'

services:
  app:
    command: "mvn spring-boot:run"
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
        - looking_for_talents

networks:
  looking_for_talents:
    external: true
